### PR TITLE
Update background.js

### PR DESCRIPTION
**Pull request by wanglongbiao**
change 'sessionid' to 'auth_token'

### CODE REVIEW

**Comment by ervine** [comment]
I found changing to 'useid' is also OK to work. What's the difference?

**Comment by jinntrance** [comment]
多谢~

**Comment by jinntrance** [comment]
fix #62

**Comment by jinntrance** [comment]
@ervine 实际上只是为了标记用户是否登录。但个人不倾向于用 cookie 记录用户相关信息，而是记录登录的这次 session 的信息，所以我比较赞同 @wanglongbiao 使用auth_token~

**Pull request merged**
